server:
  port: 8080


spring:
  redis:
    port: 6379
    host: 47.107.92.79
    jedis:
      pool:
        max-active: 8
        max-idle: 8
  rabbitmq:
    host: 47.107.92.79
    port: 5672
    username: admin
    password: admin
  data:
    solr:
      host: http://47.107.92.79:8983/solr/new_core



